spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/tax_calculator_service?characterEncoding=UTF-8&useSSL=false
  jpa:
    hibernate.ddl-auto: create-drop
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

      format_sql: true
    show-sql: true


#db:
#  username: root
#  password: root
#  driver: com.mysql.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/online_player?characterEncoding=UTF-8

server:
  port: 8080
  servlet:
    path: /api/v1